info/urls.py
from django.urls import path, include
from .views import *
from .api import *
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register("info_create", InfoCreate, basename="info_create")
app_name = "info"

urlpatterns = [
    path("info_create/", InfoCreate.as_view()),
    path("info_profile/", ProfileCreate.as_view()),
    path("email-user/", EmailUsernameOnly.as_view()),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("upload/", DocUpload.as_view(), name="doc"),
    path("user-edit/", UpdateUserAPI.as_view(), name="user-edit"),
    path("attendance/", AttendanceView.as_view(), name="attendance"),
    path("attendance/download/", DownloadAtendanceView.as_view(), name="download-attendance"),
    # path("", include(router.urls)),
]

projects/urls.py
from django.urls import path, include
from root import views
from .views import *

app_name = "projects"

urlpatterns = [
    path("", ProjectsView.as_view(), name="list"),
    path("<int:pk>/", ProjectsView.as_view(), name="detail"),
    path("<int:pk>/add-repo/", AddRepoView.as_view(), name="add-repo"),
    path("<int:pk>/add-cred/", AddCredentialView.as_view(), name="add-cred"),
    path("<int:pk>/add-doc/", AddDocView.as_view(), name="add-doc"),
    path("category", CategoryAddView.as_view(), name="category"),
]

root/urls.py
from django.urls import path, include
from root import views
from .views import *
from django.contrib.auth import views as auth_views

app_name = "root"

urlpatterns = [
    # path("administration", views.administration, name="administration"),
    path("", UserListView.as_view(), name="index"),
    path("page/", PageView.as_view(), name="page"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html", redirect_field_name="/server/"
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # path("home/", HomeView.as_view(), name="home-view"),
]

shark/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def hello_view(*args):
    return HttpResponse("Code deploy sucessfull Confirmation")


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("root.urls")),
        path("hello/", hello_view),
        path("info/", include("info.urls")),
        path("projects/", include("projects.urls")),
        path("peck/", include("peck.urls")),
        path("caffer/", include("caffer.urls")),
        path("interview/", include("interview.urls")),
    ]
    + static(f"{settings.STATIC_URL}", document_root=f"{settings.STATIC_ROOT}")
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

root/models.py
from django.db import models

# Create your models here.


class InitModel(models.Model):
    """ """

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return f"{self.created_at}"


class Technology(models.Model):
    technology = models.CharField(max_length=50)

    def __str__(self):
        return self.technology

root/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin

BASE_URL = "127.0.0.1:8000/root/"


class UserListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        users = User.objects.all()
        # import pdb; pdb.set_trace()
        paginator = Paginator(users, 10)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        ctx = {"page_obj": page_obj}
        return render(request, "index.html", ctx)


class PageView(View):
    def get(self, request):
        return render(request, "base.html", {})

root/templates/base.html
{% load static%}
{% load present %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <title>Project</title>
    <style>
        .nav-item {
            margin-left: 2px;
            padding-left: 3px;
        }
    </style>
</head>

<body>
    <div class="nav">
        {% if request.user.is_authenticated == True %}
        {% if request.user.is_superuser == True %}
        <span class="nav-item">
            <a href="{% url 'info:download-attendance' %}" class="btn btn-secondary"><i class="material-icons"></i> <span> Download
                    Attendance</span></a>
        </span>
        {% endif %}
        <span class="nav-item">
            <a href="{% url 'root:page' %}" class="btn btn-secondary"><i class="material-icons"></i> <span>Home
                    Page</span></a>
        </span>
        <span class="nav-item">
            <a href="#" class="btn btn-secondary"><i class="material-icons"></i> <span>{{request.user}}</span></a>
        </span>
        <span class="nav-item">
            <a href="{% url 'projects:list' %}" class="btn btn-secondary"><i class="material-icons"></i>
                <span>Projects</span></a>
        </span>
        <span class="nav-item">
            <a href="{% url 'root:index' %}" class="btn btn-secondary"><i class="material-icons"></i>
                <span>Users</span></a>
        </span>
        <span class="nav-item">
            <span class="btn btn-secondary" id="mark-attendance" onclick="markAttendance()"> {% is_present request.user %}</span>
        </span>
        <span class="nav-item" style="float: right;">
            <a href="{% url 'root:logout' %}" class="btn btn-secondary"><i class="material-icons"></i> <span
                    style="float: right;">Log Out</span></a>
        </span>
        {% else %}
        <a href="{% url 'root:login' %}">
            LogIn
        </a>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
    <script>
        function markAttendance() {
            location.href = "{% url 'info:attendance' %}" + "?currentUrl="+location.href 
        }
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

root/templates/homepage.html
{% load static %}

<head>
    <link rel="stylesheet" href=" {% static 'anc.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
  
                  <div class="text-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp" style="width: 185px;" alt="logo">
                    <h4 class="mt-1 mb-5 pb-1">We are The Lotus Team</h4>
                  </div>
  
                  <form>
                    <p>Please login to your ok guys account</p>
  
                    <div class="form-outline mb-4">
                      <input type="email" id="form2Example11" class="form-control" placeholder="Phone number or email address"/>
                      <label class="form-label" for="form2Example11">Username</label>
                    </div>
  
                    <div class="form-outline mb-4">
                      <input type="password" id="form2Example22" class="form-control" />
                      <label class="form-label" for="form2Example22">Password</label>
                    </div>
  
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="button">Log in</button>
                      <a class="text-muted" href="#!">Forgot password?</a>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Don't have an account?</p>
                      <button type="button" class="btn btn-outline-danger">Create new</button>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                  <h4 class="mb-4">We are more than just a company</h4>
                  <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

root/templates/index.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>User Management Data Table</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>
        body {
            color: #566787;
            background: #f5f5f5;
            font-family: 'Varela Round', sans-serif;
            font-size: 13px;
        }

        .table-responsive {
            margin: 30px 0;
        }

        .table-wrapper {
            min-width: 1000px;
            background: #fff;
            padding: 20px 25px;
            border-radius: 3px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        }

        .table-title {
            padding-bottom: 15px;
            background: #299be4;
            color: #fff;
            padding: 16px 30px;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

        .table-title h2 {
            margin: 5px 0 0;
            font-size: 24px;
        }

        .table-title .btn {
            color: #566787;
            float: right;
            font-size: 13px;
            background: #fff;
            border: none;
            min-width: 50px;
            border-radius: 2px;
            border: none;
            outline: none !important;
            margin-left: 10px;
        }

        .table-title .btn:hover,
        .table-title .btn:focus {
            color: #566787;
            background: #f2f2f2;
        }

        .table-title .btn i {
            float: left;
            font-size: 21px;
            margin-right: 5px;
        }

        .table-title .btn span {
            float: left;
            margin-top: 2px;
        }

        table.table tr th,
        table.table tr td {
            border-color: #e9e9e9;
            padding: 12px 15px;
            vertical-align: middle;
        }

        table.table tr th:first-child {
            width: 60px;
        }

        table.table tr th:last-child {
            width: 100px;
        }

        table.table-striped tbody tr:nth-of-type(odd) {
            background-color: #fcfcfc;
        }

        table.table-striped.table-hover tbody tr:hover {
            background: #f5f5f5;
        }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table td:last-child i {
            opacity: 0.9;
            font-size: 22px;
            margin: 0 5px;
        }

        table.table td a {
            font-weight: bold;
            color: #566787;
            display: inline-block;
            text-decoration: none;
        }

        table.table td a:hover {
            color: #2196F3;
        }

        table.table td a.settings {
            color: #2196F3;
        }

        table.table td a.delete {
            color: #F44336;
        }

        table.table td i {
            font-size: 19px;
        }

        table.table .avatar {
            border-radius: 50%;
            vertical-align: middle;
            margin-right: 10px;
        }

        .status {
            font-size: 30px;
            margin: 2px 2px 0 0;
            display: inline-block;
            vertical-align: middle;
            line-height: 10px;
        }

        .text-success {
            color: #10c469;
        }

        .text-info {
            color: #62c9e8;
        }

        .text-warning {
            color: #FFC107;
        }

        .text-danger {
            color: #ff5b5b;
        }

        .pagination {
            float: right;
            margin: 0 0 5px;
        }

        .pagination li a {
            border: none;
            font-size: 13px;
            min-width: 30px;
            min-height: 30px;
            color: #999;
            margin: 0 2px;
            line-height: 30px;
            border-radius: 2px !important;
            text-align: center;
            padding: 0 6px;
        }

        .pagination li a:hover {
            color: #666;
        }

        .pagination li.active a,
        .pagination li.active a.page-link {
            background: #03A9F4;
        }

        .pagination li.active a:hover {
            background: #0397d6;
        }

        .pagination li.disabled i {
            color: #ccc;
        }

        .pagination li i {
            font-size: 16px;
            padding-top: 6px
        }

        .hint-text {
            float: left;
            margin-top: 10px;
            font-size: 13px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</head>

<body>
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2>User <b> Lists </b></h2>
                        </div>
                        <div class="col-sm-7">
                            <a href="{% url 'projects:list' %}" class="btn btn-secondary"><i class="material-icons"></i> <span>Projects</span></a>

                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Joining Date</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in page_obj.object_list %}
                        <tr>
                               
                                <td>{{user.id}}</td>
                                <td><a href="{% url 'info:profile' user.id %}" target="_blank"><img src="{{user.userinformation.image.url}}" class="avatar"
                                            alt="Avatar" width="10" height="12">
                                            {% if user.get_full_name %}
                                            {{user.get_full_name}}
                                            {% else %}
                                            {{user.username}}
                                            {% endif %}
                                        
                                        </a></td>
                                <td>{{user.userinformation.joining_date}}</td>
                                <td>{{user.userinformation.role}}</td>
                                <td>{% if user.is_active == True %}<span class="status text-success"> &bull; </span>
                                    Active{% endif %} </td>
                                <td>
                                    <a href="#" class="settings" title="Settings" data-toggle="tooltip"><i
                                            class="material-icons">&#xE8B8;</i></a>
                                    <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i
                                            class="material-icons">&#xE5C9;</i></a>
                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
                {% if request.user.is_superuser %}
                <button class="btn btn-danger">
                    <a href="/admin/auth/user/add/" target="_blank">
                        Add User
                    </a>
                    
                </button>
                {% endif %}
                <div class="clearfix">
                    <div class="hint-text">Showing <b>{{page_obj.paginator.per_page}}</b> out of
                        <b>{{page_obj.paginator.count}}</b> entries</div>
                    <ul class="pagination">
                        <div class="pagination">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>

                                {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

root/templates/login.html
{% extends "base.html" %}
{% block content %}
<style>
@import "bourbon";

@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,700);
@import url(https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css);
@import url(https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css);

$shadow-color: #23203b;
$input-color: lighten(#AB9E95, 10%);
$input-border-color: #5E5165;
$button-background-color: #27AE60;

* {
  margin: 0;
  padding: 0;
}

html { 
  background: url(https://dl.dropboxusercontent.com/u/159328383/background.jpg) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

body {
  background: transparent;
}

body, input, button {
  font-family: 'Source Sans Pro', sans-serif;
}

@mixin normalize-input {
  display: block;
  width: auto;
  height: auto;
  border: none;
  outline: none;
  box-shadow: none;
  background: none;
  border-radius: 0px;
}

.login {
  padding: 15px;
  width: 400px;
  min-height: 400px;
  margin: 2% auto 0 auto;

  .heading {
    text-align: center;
    margin-top: 1%;

    h2 {
      font-size: 3em;
      font-weight: 300;
      color: rgba(255, 255, 255, 0.7);
      display: inline-block;
      padding-bottom: 5px;
      text-shadow: 1px 1px 3px $shadow-color;
    }
  }

  form {
    .input-group {
      border-bottom: 1px solid rgba(255, 255, 255, 0.1);
      border-top: 1px solid rgba(255, 255, 255, 0.1);

      &:last-of-type {
        border-top: none;
      }

      span {
        background: transparent;
        min-width: 53px;
        border: none;

        i {
          font-size: 1.5em;
          color: rgba(255, 255, 255, 0.2);
        }
      }
    }

    input.form-control {
      @include normalize-input;

      padding: 10px;
      font-size: 1.6em;
      width: 100%;
      background: transparent;
      color: $input-color;

      &:focus {
        border: none;
      }
    }

    button {
      margin-top: 20px;
      background: $button-background-color;
      border: none;
      font-size: 1.6em;
      font-weight: 300;
      padding: 5px 0;
      width: 100%;
      border-radius: 3px;
      color: lighten($button-background-color, 40%);
      border-bottom: 4px solid darken($button-background-color, 10%);

      &:hover {
        background: tint($button-background-color, 4%);
        -webkit-animation: hop 1s;
        animation: hop 1s;
      }
    }
  }
}

.float {
  display: inline-block;
  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-transition-property: transform;
  transition-property: transform;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
  box-shadow: 0 0 1px rgba(0, 0, 0, 0);
}

.float:hover, .float:focus, .float:active {
  -webkit-transform: translateY(-3px);
  transform: translateY(-3px);
}

/* Large Devices, Wide Screens */

@media only screen and (max-width : 1500px) {
}

@media only screen and (max-width : 1200px) {
  .login {
    width: 600px;
    font-size: 2em;
  }
}

@media only screen and (max-width : 1100px) {
  .login {
    margin-top: 2%;
    width: 600px;
    font-size: 1.7em;
  }
}

/* Medium Devices, Desktops */
@media only screen and (max-width : 992px) {
  .login {
    margin-top: 1%;
    width: 550px;
    font-size: 1.7em;
    min-height: 0;
  }
}

/* Small Devices, Tablets */
@media only screen and (max-width : 768px) {
  .login {
    margin-top: 0;
    width: 500px;
    font-size: 1.3em;
    min-height: 0;
  }
}

/* Extra Small Devices, Phones */ 
@media only screen and (max-width : 480px) {
  .login {

    h2 {
      margin-top: 0;
    }

    margin-top: 0;
    width: 400px;
    font-size: 1em;
    min-height: 0;
  }
}

/* Custom, iPhone Retina */ 
@media only screen and (max-width : 320px) {
  .login {
    margin-top: 0;
    width: 200px;
    font-size: 0.7em;
    min-height: 0;
  }
}


</style>
<div class="login">
    <div class="heading">
        <h2>Sign in</h2>
        <form action="{% url 'root:login' %}" method="post">
            {% csrf_token %}
            <div class="input-group input-group-lg">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input type="text" class="form-control" placeholder="Username or email" name="username">
            </div>

            <div class="input-group input-group-lg">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                <input type="password" class="form-control" placeholder="Password" name="password">
            </div>

            <button type="submit" class="float">Login</button>
        </form>
    </div>
</div>
{% endblock %}