info/urls.py
from django.urls import path, include
from .views import *
from .api import *
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register("info_create", InfoCreate, basename="info_create")
app_name = "info"

urlpatterns = [
    path("info_create/", InfoCreate.as_view()),
    path("info_profile/", ProfileCreate.as_view()),
    path("email-user/", EmailUsernameOnly.as_view()),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("upload/", DocUpload.as_view(), name="doc"),
    path("user-edit/", UpdateUserAPI.as_view(), name="user-edit"),
    path("attendance/", AttendanceView.as_view(), name="attendance"),
    path("attendance/download/", DownloadAtendanceView.as_view(), name="download-attendance"),
    # path("", include(router.urls)),
]

projects/urls.py
from django.urls import path, include
from root import views
from .views import *

app_name = "projects"

urlpatterns = [
    path("", ProjectsView.as_view(), name="list"),
    path("<int:pk>/", ProjectsView.as_view(), name="detail"),
    path("<int:pk>/add-repo/", AddRepoView.as_view(), name="add-repo"),
    path("<int:pk>/add-cred/", AddCredentialView.as_view(), name="add-cred"),
    path("<int:pk>/add-doc/", AddDocView.as_view(), name="add-doc"),
    path("category", CategoryAddView.as_view(), name="category"),
]

root/urls.py
from django.urls import path, include
from root import views
from .views import *
from django.contrib.auth import views as auth_views

app_name = "root"

urlpatterns = [
    # path("administration", views.administration, name="administration"),
    path("", UserListView.as_view(), name="index"),
    path("page/", PageView.as_view(), name="page"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html", redirect_field_name="/server/"
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # path("home/", HomeView.as_view(), name="home-view"),
]

shark/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def hello_view(*args):
    return HttpResponse("Code deploy sucessfull Confirmation")


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("root.urls")),
        path("hello/", hello_view),
        path("info/", include("info.urls")),
        path("projects/", include("projects.urls")),
        path("peck/", include("peck.urls")),
        path("caffer/", include("caffer.urls")),
        path("interview/", include("interview.urls")),
    ]
    + static(f"{settings.STATIC_URL}", document_root=f"{settings.STATIC_ROOT}")
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

projects/models.py
from django.db import models
from django.urls import reverse
from root.models import InitModel
from django.contrib.auth.models import User

# Create your models here.

REPO_TYPE = (
    ("github", "github"),
    ("gitlab", "gitlab"),
    ("bitbucket", "bitbucket"),
    ("zip", "zip"),
)
AUTH_TYPE = (
    ("google", "google"),
    ("username_password", "username_password"),
    ("other", "other"),
)


class Project(InitModel):
    name = models.CharField(max_length=50)
    about = models.TextField(
        null=True, blank=True, help_text="Short description about the project"
    )
    logo = models.FileField(blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name}"


class BaseProject(InitModel):
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, blank=True, null=True
    )
    username = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.project}"

    class Meta:
        abstract = True


class Repository(BaseProject):
    repo_type = models.CharField(
        choices=REPO_TYPE, max_length=50, blank=True, null=True
    )
    auth_type = models.CharField(
        choices=AUTH_TYPE, max_length=50, blank=True, null=True
    )
    url = models.URLField(blank=True, null=True)


class Category(InitModel):
    name = models.CharField(max_length=50)
    about = models.TextField(
        null=True, blank=True, help_text="Short description about the category"
    )

    def __str__(self) -> str:
        return f"{self.name}"


class Credentials(BaseProject):
    credential_type = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Describe what this credentials are about",
    )
    url = models.URLField(
        blank=True, null=True, help_text="URL for which credentials are being added"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        help_text="Category such as staging server aws or jira",
    )
    file = models.FileField(upload_to="auth_files", null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.credential_type}"


class ProjectDocument(BaseProject):
    name = models.CharField(max_length=50)
    url = models.URLField(blank=True, null=True)
    file = models.FileField(upload_to="auth_files", null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.name}- {self.project}"


class Extra(InitModel):
    extra = models.JSONField(default=dict)
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self) -> str:
        return f"{self.project}"


class AssignedProject(InitModel):
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="projects"
    )
    projects = models.ManyToManyField(Project, blank=True)

    def __str__(self) -> str:
        return f"{self.user}"

projects/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from .models import Repository, Project, Credentials, ProjectDocument


class RepositoryForm(forms.ModelForm):
    class Meta:
        model = Repository
        exclude = ("project",)


class CredentialsFrom(forms.ModelForm):
    class Meta:
        model = Credentials
        exclude = ("project",)


class ProjectDocumentFrom(forms.ModelForm):
    class Meta:
        model = ProjectDocument
        exclude = ("project",)

projects/views.py
import re
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Category, Credentials, Project, Repository, ProjectDocument
from .forms import RepositoryForm, CredentialsFrom, ProjectDocumentFrom
from django.views.generic.edit import CreateView

BASE_URL = "127.0.0.1:8000/root/"


class ProjectsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if pk := kwargs.get("pk"):
            ctx = {
                "project": Project.objects.get(pk=pk),
                "repository_from": RepositoryForm(),
                "credentials_form": CredentialsFrom(),
                "project_doc_from": ProjectDocumentFrom(),
            }
            return render(request, "project-detail.html", ctx)
        projects = Project.objects.all()
        if not request.user.is_superuser:
            # import pdb; pdb.set_trace()
            projects = request.user.projects.projects.all() if  hasattr(request.user, 'projects') else []
        ctx = {"projects": projects}
        return render(request, "projects.html", ctx)


class AddRepoView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwrags):
        form = RepositoryForm(
            request.POST,
        )
        if form.is_valid():
            project = Project.objects.get(pk=kwrags.get("pk"))
            cleaned_data = form.cleaned_data
            cleaned_data["project"] = project
            Repository.objects.create(**cleaned_data)
        return redirect(reverse("projects:list"))


class AddCredentialView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwrags):
        form = CredentialsFrom(request.POST, request.FILES)
        if form.is_valid():
            project = Project.objects.get(pk=kwrags.get("pk"))
            cleaned_data = form.cleaned_data
            cleaned_data["project"] = project
            Credentials.objects.create(**cleaned_data)
        return redirect(reverse("projects:list"))


class AddDocView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwrags):
        form = ProjectDocumentFrom(request.POST, request.FILES)
        if form.is_valid():
            project = Project.objects.get(pk=kwrags.get("pk"))
            cleaned_data = form.cleaned_data
            cleaned_data["project"] = project
            ProjectDocument.objects.create(**cleaned_data)
        return redirect(reverse("projects:list"))


class CategoryAddView(LoginRequiredMixin, CreateView):
    model = Category
    fields = "__all__"

    def get_success_url(self) -> str:
        return reverse("projects:list")


AddDocView

projects/templates/projects.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Project  Management Data Table</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>
        body {
            color: #566787;
            background: #f5f5f5;
            font-family: 'Varela Round', sans-serif;
            font-size: 13px;
        }

        .table-responsive {
            margin: 30px 0;
        }

        .table-wrapper {
            min-width: 1000px;
            background: #fff;
            padding: 20px 25px;
            border-radius: 3px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        }

        .table-title {
            padding-bottom: 15px;
            background: #299be4;
            color: #fff;
            padding: 16px 30px;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

        .table-title h2 {
            margin: 5px 0 0;
            font-size: 24px;
        }

        .table-title .btn {
            color: #566787;
            float: right;
            font-size: 13px;
            background: #fff;
            border: none;
            min-width: 50px;
            border-radius: 2px;
            border: none;
            outline: none !important;
            margin-left: 10px;
        }

        .table-title .btn:hover,
        .table-title .btn:focus {
            color: #566787;
            background: #f2f2f2;
        }

        .table-title .btn i {
            float: left;
            font-size: 21px;
            margin-right: 5px;
        }

        .table-title .btn span {
            float: left;
            margin-top: 2px;
        }

        table.table tr th,
        table.table tr td {
            border-color: #e9e9e9;
            padding: 12px 15px;
            vertical-align: middle;
        }

        table.table tr th:first-child {
            width: 60px;
        }

        table.table tr th:last-child {
            width: 100px;
        }

        table.table-striped tbody tr:nth-of-type(odd) {
            background-color: #fcfcfc;
        }

        table.table-striped.table-hover tbody tr:hover {
            background: #f5f5f5;
        }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table td:last-child i {
            opacity: 0.9;
            font-size: 22px;
            margin: 0 5px;
        }

        table.table td a {
            font-weight: bold;
            color: #566787;
            display: inline-block;
            text-decoration: none;
        }

        table.table td a:hover {
            color: #2196F3;
        }

        table.table td a.settings {
            color: #2196F3;
        }

        table.table td a.delete {
            color: #F44336;
        }

        table.table td i {
            font-size: 19px;
        }

        table.table .avatar {
            border-radius: 50%;
            vertical-align: middle;
            margin-right: 10px;
        }

        .status {
            font-size: 30px;
            margin: 2px 2px 0 0;
            display: inline-block;
            vertical-align: middle;
            line-height: 10px;
        }

        .text-success {
            color: #10c469;
        }

        .text-info {
            color: #62c9e8;
        }

        .text-warning {
            color: #FFC107;
        }

        .text-danger {
            color: #ff5b5b;
        }

        .pagination {
            float: right;
            margin: 0 0 5px;
        }

        .pagination li a {
            border: none;
            font-size: 13px;
            min-width: 30px;
            min-height: 30px;
            color: #999;
            margin: 0 2px;
            line-height: 30px;
            border-radius: 2px !important;
            text-align: center;
            padding: 0 6px;
        }

        .pagination li a:hover {
            color: #666;
        }

        .pagination li.active a,
        .pagination li.active a.page-link {
            background: #03A9F4;
        }

        .pagination li.active a:hover {
            background: #0397d6;
        }

        .pagination li.disabled i {
            color: #ccc;
        }

        .pagination li i {
            font-size: 16px;
            padding-top: 6px
        }

        .hint-text {
            float: left;
            margin-top: 10px;
            font-size: 13px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</head>

<body>
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2>Projects <b> Lists </b></h2>
                        </div>
                        <div class="col-sm-7">
                            <a href="{% url 'root:index' %}" class="btn btn-secondary"><i class="material-icons"></i> <span>Users</span></a>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}

                        <tr>
                            <td>
                                <a href="{% url 'projects:detail' project.id %}">
                                    {{project.id}}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'projects:detail' project.id %}">
                                    {{project.name}}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'projects:detail' project.id %}">
                                    {{project.about}}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                {% if request.user.is_superuser %}
                <button type="button" class="btn btn-danger">
                    <a href="/admin/projects/project/add/" target="_blank">
                        Add Project
                    </a>
                    
                </button>
                {% endif %}
            </div>
        </div>
    </div>
</body>
{% endblock %}