info/urls.py
from django.urls import path, include
from .views import *
from .api import *
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register("info_create", InfoCreate, basename="info_create")
app_name = "info"

urlpatterns = [
    path("info_create/", InfoCreate.as_view()),
    path("info_profile/", ProfileCreate.as_view()),
    path("email-user/", EmailUsernameOnly.as_view()),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("upload/", DocUpload.as_view(), name="doc"),
    path("user-edit/", UpdateUserAPI.as_view(), name="user-edit"),
    path("attendance/", AttendanceView.as_view(), name="attendance"),
    path("attendance/download/", DownloadAtendanceView.as_view(), name="download-attendance"),
    # path("", include(router.urls)),
]

projects/urls.py
from django.urls import path, include
from root import views
from .views import *

app_name = "projects"

urlpatterns = [
    path("", ProjectsView.as_view(), name="list"),
    path("<int:pk>/", ProjectsView.as_view(), name="detail"),
    path("<int:pk>/add-repo/", AddRepoView.as_view(), name="add-repo"),
    path("<int:pk>/add-cred/", AddCredentialView.as_view(), name="add-cred"),
    path("<int:pk>/add-doc/", AddDocView.as_view(), name="add-doc"),
    path("category", CategoryAddView.as_view(), name="category"),
]

shark/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def hello_view(*args):
    return HttpResponse("Code deploy sucessfull Confirmation")


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("root.urls")),
        path("hello/", hello_view),
        path("info/", include("info.urls")),
        path("projects/", include("projects.urls")),
        path("peck/", include("peck.urls")),
        path("caffer/", include("caffer.urls")),
        path("interview/", include("interview.urls")),
    ]
    + static(f"{settings.STATIC_URL}", document_root=f"{settings.STATIC_ROOT}")
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

projects/models.py
from django.db import models
from django.urls import reverse
from root.models import InitModel
from django.contrib.auth.models import User

# Create your models here.

REPO_TYPE = (
    ("github", "github"),
    ("gitlab", "gitlab"),
    ("bitbucket", "bitbucket"),
    ("zip", "zip"),
)
AUTH_TYPE = (
    ("google", "google"),
    ("username_password", "username_password"),
    ("other", "other"),
)


class Project(InitModel):
    name = models.CharField(max_length=50)
    about = models.TextField(
        null=True, blank=True, help_text="Short description about the project"
    )
    logo = models.FileField(blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name}"


class BaseProject(InitModel):
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, blank=True, null=True
    )
    username = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.project}"

    class Meta:
        abstract = True


class Repository(BaseProject):
    repo_type = models.CharField(
        choices=REPO_TYPE, max_length=50, blank=True, null=True
    )
    auth_type = models.CharField(
        choices=AUTH_TYPE, max_length=50, blank=True, null=True
    )
    url = models.URLField(blank=True, null=True)


class Category(InitModel):
    name = models.CharField(max_length=50)
    about = models.TextField(
        null=True, blank=True, help_text="Short description about the category"
    )

    def __str__(self) -> str:
        return f"{self.name}"


class Credentials(BaseProject):
    credential_type = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Describe what this credentials are about",
    )
    url = models.URLField(
        blank=True, null=True, help_text="URL for which credentials are being added"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        help_text="Category such as staging server aws or jira",
    )
    file = models.FileField(upload_to="auth_files", null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.credential_type}"


class ProjectDocument(BaseProject):
    name = models.CharField(max_length=50)
    url = models.URLField(blank=True, null=True)
    file = models.FileField(upload_to="auth_files", null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.name}- {self.project}"


class Extra(InitModel):
    extra = models.JSONField(default=dict)
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self) -> str:
        return f"{self.project}"


class AssignedProject(InitModel):
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="projects"
    )
    projects = models.ManyToManyField(Project, blank=True)

    def __str__(self) -> str:
        return f"{self.user}"

projects/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from .models import Repository, Project, Credentials, ProjectDocument


class RepositoryForm(forms.ModelForm):
    class Meta:
        model = Repository
        exclude = ("project",)


class CredentialsFrom(forms.ModelForm):
    class Meta:
        model = Credentials
        exclude = ("project",)


class ProjectDocumentFrom(forms.ModelForm):
    class Meta:
        model = ProjectDocument
        exclude = ("project",)

projects/views.py
import re
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Category, Credentials, Project, Repository, ProjectDocument
from .forms import RepositoryForm, CredentialsFrom, ProjectDocumentFrom
from django.views.generic.edit import CreateView

BASE_URL = "127.0.0.1:8000/root/"


class ProjectsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if pk := kwargs.get("pk"):
            ctx = {
                "project": Project.objects.get(pk=pk),
                "repository_from": RepositoryForm(),
                "credentials_form": CredentialsFrom(),
                "project_doc_from": ProjectDocumentFrom(),
            }
            return render(request, "project-detail.html", ctx)
        projects = Project.objects.all()
        if not request.user.is_superuser:
            # import pdb; pdb.set_trace()
            projects = request.user.projects.projects.all() if  hasattr(request.user, 'projects') else []
        ctx = {"projects": projects}
        return render(request, "projects.html", ctx)


class AddRepoView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwrags):
        form = RepositoryForm(
            request.POST,
        )
        if form.is_valid():
            project = Project.objects.get(pk=kwrags.get("pk"))
            cleaned_data = form.cleaned_data
            cleaned_data["project"] = project
            Repository.objects.create(**cleaned_data)
        return redirect(reverse("projects:list"))


class AddCredentialView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwrags):
        form = CredentialsFrom(request.POST, request.FILES)
        if form.is_valid():
            project = Project.objects.get(pk=kwrags.get("pk"))
            cleaned_data = form.cleaned_data
            cleaned_data["project"] = project
            Credentials.objects.create(**cleaned_data)
        return redirect(reverse("projects:list"))


class AddDocView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwrags):
        form = ProjectDocumentFrom(request.POST, request.FILES)
        if form.is_valid():
            project = Project.objects.get(pk=kwrags.get("pk"))
            cleaned_data = form.cleaned_data
            cleaned_data["project"] = project
            ProjectDocument.objects.create(**cleaned_data)
        return redirect(reverse("projects:list"))


class CategoryAddView(LoginRequiredMixin, CreateView):
    model = Category
    fields = "__all__"

    def get_success_url(self) -> str:
        return reverse("projects:list")


AddDocView

projects/templates/projects/add-cred.html
<button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#add-project-credentials"
    aria-expanded="false" aria-controls="collapseExample">
    Add More Credentials
</button>

<div class="modal fade" id="add-project-credentials" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Project Credentials Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">
                <form method="post" action="{% url 'projects:add-cred' project.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in credentials_form %}
                    <div class="col">
                        {% if field.field.widget.input_type == "select" %}
                        <div class="form-group focused">
                            <label class="form-control-label" for="{{ field.id_for_label }}">
                                {{ field.label}}</label>
                            <select type={{field.widget.input_type}} id="{{ field.id_for_label }}"
                                name="{{field.html_name}}" class="form-control form-control-alternative"
                                placeholder="Username" value=" {{object.username}}">
                                {% for choice in field.field.choices %}
                                <option value="{{choice.0}}">
                                    {{choice.1}}
                                </option>
                                {% endfor %}
                            </select>
                            {% if field.help_text %}
                            <span class="help">{{ field.help_text|safe }}</span>
                            {% if field.html_name == "category" %}
                            <span class="help"> <a href="{% url 'projects:category' %}"> Add category</a></span>
                            {% endif %}
                            {% endif %}
                        </div>
                        {% else %}
                        <div class="form-group focused">
                            <label class="form-control-label" for="{{ field.id_for_label }}">
                                {{ field.label}}
                            </label>
                            <input type={{field.field.widget.input_type}} id="{{ field.id_for_label }}"
                                name="{{field.html_name}}" class="form-control form-control-alternative"
                                placeholder="Username" value=" {{object.username}}">
                                {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
        </div>
    </div>
</div>

projects/templates/projects/add-doc.html
<button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#add-project-doc"
    aria-expanded="false" aria-controls="collapseExample">
    Add More Doc
</button>

<div class="modal fade" id="add-project-doc" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Project Documents Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'projects:add-doc' project.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                        {{ project_doc_from.as_p }}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

projects/templates/projects/add-repo.html
<button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#add-project-repo"
    aria-expanded="false" aria-controls="collapseExample">
    Add More Info
</button>

<div class="modal fade" id="add-project-repo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Project repo Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'projects:add-repo' project.id %}">
                    {% csrf_token %}
                    {% for field in repository_from %}
                    {{field.field.input_type}}
                    <div class="col">
                        {% if field.field.widget.input_type == "select" %}
                        <div class="form-group focused">
                            <label class="form-control-label" for="{{ field.id_for_label }}">
                                {{ field.label }}</label>
                            <select type={{field.widget.input_type}} id="{{ field.id_for_label }}"
                                name="{{field.html_name}}" class="form-control form-control-alternative"
                                placeholder="Username" value=" {{object.username}}">
                                {% for choice in field.field.choices %}
                                <option value="{{choice.0}}">
                                    {{choice.1}}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                        {% else %}
                        <div class="form-group focused">
                            <label class="form-control-label" for="{{ field.id_for_label }}">
                                {{ field.label}}</label>
                            <input type={{field.field.widget.input_type}} id="{{ field.id_for_label }}"
                                name="{{field.html_name}}" class="form-control form-control-alternative"
                                placeholder="Username" value=" {{object.username}}">
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

projects/templates/projects/category_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

projects/templates/projects/cred-info.html
<table class="table table-striped">
    <thead>
        <tr>
          <th scope="col">Category</th>
          <th scope="col">Credential Type</th>
          <th scope="col">URL</th>
          <th scope="col">Username </th>
          <th scope="col">Email </th>
          <th scope="col">Password </th>
          <th scope="col">File </th>
        </tr>
      </thead>
      <tbody>
        {% for obj in project.credentials_set.all %}
        <tr>
          <td>{{obj.category }}</td>
          <td>{{obj.credential_type }}</td>
          <td>{{obj.url }}</td>
          <td>{{obj.username }}</td>
          <td>{{obj.email }}</td>
          <td>{{obj.password }}</td>
          <td>{% if obj.file %} <a href="{{ obj.file.url }}" target="_blank">
              View
          </a>
          {% else %} - {% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
  </table>

projects/templates/projects/list-doc.html
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">URL</th>
            <th scope="col">Username </th>
            <th scope="col">Email </th>
            <th scope="col">Password </th>
            <th scope="col">File </th>
        </tr>
    </thead>
    <tbody>
        {% for obj in project.projectdocument_set.all %}
        <tr>
            <td>{% if obj.name %} {{obj.name }} {% else %} - {% endif %}</td>
            <td>{% if obj.url %} {{obj.url }} {% else %} - {% endif %}</td>
            <td>{% if obj.username %} {{obj.username }} {% else %} - {% endif %}</td>
            <td>{% if obj.email %} {{obj.email }} {% else %} - {% endif %}</td>
            <td>{% if obj.password %} {{obj.password }} {% else %} - {% endif %}</td>
            <td>{% if obj.file %} <a href="{{ obj.file.url }}" target="_blank">
                    View
                </a>
                {% else %} - {% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

projects/templates/projects/repo-info.html
    <table class="table table-striped">
        <thead>
            <tr>
              <th scope="col">Repo Type</th>
              <th scope="col">Auth Type</th>
              <th scope="col">URL</th>
              <th scope="col">Username </th>
              <th scope="col">Email </th>
              <th scope="col">Password </th>
            </tr>
          </thead>
          <tbody>
            {% for obj in project.repository_set.all %}
            <tr>
              <td>{{obj.repo_type }}</td>
              <td>{{obj.auth_type }}</td>
              <td>{{obj.url }}</td>
              <td>{{obj.username }}</td>
              <td>{{obj.email }}</td>
              <td>{{obj.password }}</td>
            </tr>
            {% endfor %}
          </tbody>
      </table>